### ISSUE TITLE
facial detail not smooth

### ISSUE THREAD

**Issue by xinedison** [apchenstu/Facial_Details_Synthesis#11]
Hi, apchenstu. 
Thank you for sharing this code. 

I compiled the source code and generate the mesh geometry from the build tools by running facialDetail.py. And the surface seems strange like follow figure, it is not smooth. Is there something I did wrong. Because my machine has not 6 GB gpu memory， so I changed the batch_size for test to 16.

The out put mesh geometry
![edfd67920d75a5bea212b6e57c05241](https://user-images.githubusercontent.com/4470974/64397578-5caba200-d094-11e9-8ed4-201acf278918.png)

The rendered model, texture and original file like following: 
![4fe52e094597d0049e6810389640328](https://user-images.githubusercontent.com/4470974/64397784-f83d1280-d094-11e9-9e32-b6833adea256.png)

**Comment by apchenstu** [comment]
This issue is not caused by batch size, it must something wrong on the texture coordinate. Did you try this picture with the released packed? Also could you show me how did you compile the proxyEstimator? Thanks.

**Comment by xinedison** [comment]
Thanks for your reply.   The release version works fine.
The error must be in compiled version. 
I compiled the proxyEstimator with opencv3 (installed by vcpkg) CMake 3.15.2 and visual studio 2017. And changed some exe (texture render, landmarkDetector, proxyEstimator) path to the real path of my computer.

**Comment by XIAO-RUI-RUI** [comment]
The distorted wrong texture map and 3D Model, is caused by the size of input picture.
From this code form proxyPredictor.py, we can find the picture'size decide the landmark-scale of the result picture.
`line 177:         landmark_scale = max(img.size[0], img.size[1])/256.0`
And
`line 95:        cmd = 'fit-model.exe -i '+ imagePath+' -l '+ptsPath+' -o '+savePath+' --save-texture 0 --save-wireframe 0 --landmark-scale '+ str(1)+' '+file_path`
So we'd better make input picture's size is the mutiple of the 256.0.
